name: Verify Windows install + artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download CouchDB installer
      run: |
        curl https://couchdbneighbourhoodie.fra1.digitaloceanspaces.com/downloads/3.3.0/win/apache-couchdb-3.3.0.msi --output apache-couchdb-3.3.0.msi
    - name: Set up CouchDB
      run: |
        echo ${{ runner.temp }}
        echo someTEXT > ${{ runner.temp }}\log.txt
        echo first
        msiexec /i apache-couchdb-3.3.0.msi /quiet APPLICATIONFOLDER=${{ runner.temp }}\CouchDB COOKIEVALUE=abcdefghijklmo INSTALLSERVICE=1 ADMINUSER=admin ADMINPASSWORD=hunter2 /norestart /l* ${{ runner.temp }}\log.txt
        mkdir ${{ runner.temp }}\Testing
        more ${{ runner.temp }}\log.txt
    # echo temp gives the location of the temp-directory
    # then I add someText into the new log.txt file
    # echo something to know I passed that step
    # run msiexec with would use the tempDirectory's subfolder (CouchDB) and log the install into said file
    # create a temporary testing folder
    # nothing was added to the log-file
    - name: Check CouchDB setup
      run: |
        cd ..\..\..
        tree d:
    # change to root folder and do a tree command. The CouchDB folder is not created, but the temporary testing folder is there
    - name: Test CouchDB
      run: |
        curl -f http://127.0.0.1:5984/
    - name: Test CouchDB authentication
      run: |
        curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": "admin", "password": "hunter2"}' http://127.0.0.1:5984/_session
    - name: Set up git environment variables
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"
    - name: Checkout content
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-windows.txt
    - name: Check installation - should fail
      run: |
        python3 -m pasta_eln.installationTools
    - name: Installation
      run: |
        python3 -m pasta_eln.installationTools install
    - name: Upload couchdb log
      uses: actions/upload-artifact@v3
      with:
        name: couchDB.log
        path: C:\Program Files\Apache CouchDB\var\log\couchdb.log
      if: ${{ always() }}
